### ISSUE TITLE
Dependency tree for DJ Bot

### ISSUE THREAD

**Issue by cleemullins** [bookRa/Microsoft-DJ-Bot#1]
When I looked at the [package.json](https://github.com/bookRa/Microsoft-DJ-Bot/blob/master/package.json) for the DJ bot, I see some dependencies that have unexpected versions:
```
"botbuilder": "^4.0.6",
"botbuilder-dialogs": "^4.1.3",
"botframework-config": "^4.0.6",
```

Normally I would expect these to all be the same. The minor version difference (4.0 vs 4.1 for the dialogs) seems like it might cause a problem. 

What's your thinking here?

**Comment by bookRa** [comment]
Hi Chris,
Yes, that was an oversight on my part. I used the Yeoman build tool (which is using `botbuilder@4.06`)  and chose Echo bot--instead of Basic which has `botbuilder-dialogs` built in--, I installed `botbuilder-dialogs` with npm and didn't check the versions.

**Comment by cleemullins** [comment]
Ah. 

We'll be refreshing + publishing new Yeoman templates next week, against v4.1.5, so hopefully this problem will go away.
